services:
  mlflow:
    build:
      dockerfile: Dockerfile
    container_name: mlflow_server_compose
    depends_on:
      - db
    environment:
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlruns
      MLFLOW_BACKEND_STORE_URI: mysql://mlflow_user:mlflow@db:3306/mlflow_database?charset=utf8mb4
    command:
      [
        "mlflow","server",
        "--host","0.0.0.0",
        "--port","5000",
      ]
    volumes:
      - mlruns:/mlruns
    ports:
      - "5000:5000"
  db:
      restart: always
      image: mysql/mysql-server@sha256:5b40d96b11333570143d98d3a74100fefadb9abb17b27a95dbc9ad33544ec142
      container_name: mlflow_db
      ports:
          - "3306:3306"
      environment:
          - MYSQL_DATABASE=mlflow_database
          - MYSQL_USER=mlflow_user
          - MYSQL_PASSWORD=mlflow
          - MYSQL_ROOT_PASSWORD=mysql
      volumes:
          - dbdata:/var/lib/mysql

volumes:
  mlruns:
  dbdata:
